name: Build Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: |
            frontend/package-lock.json
            backend/package-lock.json

      - name: Frontend - Install & Build
        working-directory: ./frontend
        run: |
          npm install
          npm run build

      - name: Backend - Install
        working-directory: ./backend
        run: |
          npm install

      - name: Start Services with Docker Compose
        uses: docker/compose-action@v2
        with:
          files: docker-compose.yml
          pull: true
          up: true
          build: true

      - name: Health Check
        run: |
          curl -f http://localhost:3000 || exit 1
          curl -f http://localhost:3001/api/pokemon/pikachu || exit 1
